spring.application.name=api-gateway
server.port=8080

# Write Service
spring.cloud.gateway.routes[0].id=write-service
spring.cloud.gateway.routes[0].uri=http://write-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/urls,/urls/**
spring.cloud.gateway.routes[0].predicates[1]=Method=POST

# Read Service
spring.cloud.gateway.routes[1].id=read-service
spring.cloud.gateway.routes[1].uri=http://read-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/urls,/urls/**
spring.cloud.gateway.routes[1].predicates[1]=Method=GET

# Redirect Service
spring.cloud.gateway.routes[2].id=redirect-service
spring.cloud.gateway.routes[2].uri=http://redirect-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/**
spring.cloud.gateway.routes[2].predicates[1]=Method=GET

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty.http.client=DEBUG