spring.application.name=url-shortener
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortner
spring.datasource.username=appuser
spring.datasource.password=supersecret


spring.jpa.hibernate.ddl-auto=update